[build]
  command = "" # Replace with your build command
  publish = "build"         # Replace with your build output directory

[dev]
  command = "npm start"     # Replace with your development command
